export const globalKeys = {
    Race: [
        { name: "Human", value: "Human" },
        { name: "Chimera", value: "Chimera" },
        { name: "Elf", value: "Elf" },
        { name: "Catfolk", value: "Catfolk" },
        { name: "Lupine", value: "Lupine" },
        { name: "Orc", value: "Orc" },
        { name: "Minotaur", value: "Minotaur" },
        { name: "Cowgirl", value: "Cowgirl" },
        { name: "Taeleer", value: "Taeleer" },
        { name: "Bearfolk", value: "Bearfolk" },
        { name: "Sheepfolk", value: "Sheepfolk" },
        { name: "Foxmorph", value: "Foxmorph" },
        { name: "Kitsune", value: "Kitsune" },
        { name: "Harpy", value: "Harpy" },
        { name: "Manticore", value: "Manticore" },
        { name: "Gnoll", value: "Gnoll" },
        { name: "Salamander", value: "Salamander" },
        { name: "Goblin", value: "Goblin" },
        { name: "Tanuki", value: "Tanuki" },
        { name: "Mothfolk", value: "Mothfolk" },
        { name: "Marefolk", value: "Marefolk" },
        { name: "Spiderfolk", value: "Spiderfolk" },
        { name: "Leothran", value: "Leothran" },
        { name: "Pexighast", value: "Pexighast" },
        { name: "Deerfolk", value: "Deerfolk" },
        { name: "Catmorph", value: "Catmorph" },
        { name: "Siorcanna", value: "Siorcanna" },
        { name: "Plantfolk", value: "Plantfolk" },
        { name: "Vesparan", value: "Vesparan" },
        { name: "Demonmorph", value: "Demonmorph" },
        { name: "Centaur", value: "Centaur" }
    ],
    Taxon: [
        { name: "Humanoid", value: 1 },
        { name: "Beast", value: 2 },
        { name: "Demon", value: 3 },
        { name: "Plant", value: 4 },
        { name: "Ethereal", value: 5 },
        { name: "Undead", value: 6 },
        { name: "Construct", value: 7 },
        { name: "Fey", value: 8 }
    ],
    Class: [
        { name: "None", value: 0 },
        { name: "Warrior", value: 1 },
        { name: "Thief", value: 2 },
        { name: "Wmage", value: 3 },
        { name: "Bmage", value: 4 },
        { name: "Charmer", value: 5 }
    ],
    Background: [
        { name: "None", value: 0 },
        { name: "Noblescion", value: 1 },
        { name: "Minstrel", value: 2 },
        { name: "Soldier", value: 3 },
        { name: "Arcanist", value: 4 },
        { name: "Barbarian", value: 5 },
        { name: "Scholar", value: 6 },
        { name: "Slumrat", value: 7 },
        { name: "Acolyte", value: 8 },
        { name: "Hunter", value: 9 },
        { name: "Courtesan", value: 10 }
    ],
    TFType: [
        { name: "Everything", value: 0 },
        { name: "Body", value: 1 },
        { name: "Limbs", value: 2 },
        { name: "Face", value: 3 },
        { name: "Head", value: 4 },
        { name: "Tail", value: 5 },
        { name: "Cock", value: 6 },
        { name: "Milk", value: 7 },
        { name: "Balls", value: 8 },
        { name: "Breasts", value: 9 },
        { name: "Butt", value: 10 },
        { name: "Pussy", value: 11 },
        { name: "Cum", value: 12 },
        { name: "Feracity", value: 13 }
    ],
    BodyType: [
        { name: "None", value: -1 },
        { name: "Unspecified", value: 0 },
        { name: "Human", value: 1 },
        { name: "Orc", value: 2 },
        { name: "Canine", value: 3 },
        { name: "Feline", value: 4 },
        { name: "Sylvan", value: 5 },
        { name: "Elf", value: 5 },
        { name: "Equine", value: 6 },
        { name: "Vulpine", value: 7 },
        { name: "Snake", value: 8 },
        { name: "Mothrine", value: 9 },
        { name: "Goat", value: 10 },
        { name: "Swine", value: 11 },
        { name: "Shark", value: 12 },
        { name: "Bee", value: 13 },
        { name: "Draconic", value: 14 },
        { name: "Kangaroo", value: 15 },
        { name: "Anemone", value: 16 },
        { name: "Avian", value: 17 },
        { name: "Tentacle", value: 18 },
        { name: "Demonic", value: 19 },
        { name: "Frog", value: 20 },
        { name: "Gooey", value: 21 },
        { name: "Bovine", value: 22 },
        { name: "Lupine", value: 23 },
        { name: "Mouse", value: 24 },
        { name: "Sheep", value: 25 },
        { name: "Lapine", value: 26 },
        { name: "Arachnid", value: 27 },
        { name: "Succubus", value: 28 },
        { name: "Dove", value: 29 },
        { name: "Scorpion", value: 30 },
        { name: "Cuntsnake", value: 30 },
        { name: "Hyena", value: 31 },
        { name: "Salamander", value: 32 },
        { name: "Tanuki", value: 33 },
        { name: "Humanmasked", value: 34 },
        { name: "Leothran", value: 36 },
        { name: "Plant", value: 37 },
        { name: "Bushel", value: 38 },
        { name: "Ursine", value: 39 },
        { name: "Cervine", value: 40 },
        { name: "Catmorph", value: 41 },
        { name: "Lizard", value: 42 },
        { name: "Hornet", value: 43 }
    ],
    BodyTag: [
        { name: "Internal", value: 0 },
        { name: "Knotted", value: 1 },
        { name: "Gooey", value: 2 },
        { name: "Tapered", value: 3 },
        { name: "Flared", value: 4 },
        { name: "Blunt", value: 5 },
        { name: "Prehensile", value: 6 },
        { name: "Stinger Based", value: 7 },
        { name: "Stinger Tipped", value: 8 },
        { name: "Nubby", value: 9 },
        { name: "Amorphous", value: 10 },
        { name: "Smooth", value: 11 },
        { name: "Ribbed", value: 12 },
        { name: "Foreskinned", value: 13 },
        { name: "Double Headed", value: 14 },
        { name: "Thick", value: 15 },
        { name: "Sticky", value: 16 },
        { name: "Fluffy", value: 17 },
        { name: "Lubricated", value: 18 },
        { name: "Long", value: 19 },
        { name: "Hollow", value: 20 },
        { name: "Squishy", value: 21 },
        { name: "Angular", value: 22 },
        { name: "Freckled", value: 23 },
        { name: "Muzzled", value: 24 },
        { name: "Beak", value: 25 },
        { name: "Furred", value: 26 },
        { name: "Tusked", value: 27 },
        { name: "Refined", value: 28 },
        { name: "Scaled", value: 29 },
        { name: "Feathered", value: 30 },
        { name: "Chitinous", value: 31 },
        { name: "Aphrodisiac Laced", value: 32 },
        { name: "Paws", value: 33 },
        { name: "Digitigrade", value: 34 },
        { name: "Plantigrade", value: 35 },
        { name: "Heels", value: 36 },
        { name: "Hooves", value: 37 },
        { name: "Sheathed", value: 38 },
        { name: "Pumped", value: 39 },
        { name: "Slightly Pumped", value: 40 },
        { name: "Spiked", value: 41 },
        { name: "Magicock", value: 42 },
        { name: "Arctic", value: 43 },
        { name: "Maned", value: 44 },
        { name: "Floppy", value: 45 },
        { name: "Wooly", value: 46 },
        { name: "Ignan", value: 47 },
        { name: "Antennae", value: 48 },
        { name: "Curly", value: 49 },
        { name: "Bushel", value: 50 },
        { name: "Short", value: 51 },
        { name: "Hipped", value: 52 },
        { name: "Flushed", value: 53 }
    ],
    FluidType: [
        { name: "None", value: -1 },
        { name: "Unspecified", value: 0 },
        { name: "Girlcum", value: 1 },
        { name: "Cum", value: 2 },
        { name: "Honey", value: 3 },
        { name: "Milk", value: 4 },
        { name: "Chocolate Milk", value: 5 },
        { name: "Strawberry Milk", value: 6 }
    ],
    SkinType: [
        { name: "None", value: -1 },
        { name: "Unspecified", value: 0 },
        { name: "Latex", value: 1 },
        { name: "Plant", value: 2 },
        { name: "Bark", value: 3 },
        { name: "Fur", value: 4 },
        { name: "Feathers", value: 5 },
        { name: "Skin", value: 6 },
        { name: "Scales", value: 7 },
        { name: "Chitin", value: 8 },
        { name: "Goo", value: 9 }
    ],
    NippleType: [
        { name: "None", value: -1 },
        { name: "Unspecified", value: 0 },
        { name: "Fuckable", value: 1 },
        { name: "Flat", value: 2 },
        { name: "Inverted", value: 3 },
        { name: "Lipples", value: 4 },
        { name: "Tentacled", value: 5 },
        { name: "Dick", value: 6 },
        { name: "Normal", value: 7 }
    ],
    HairType: [
        { name: "None", value: -1 },
        { name: "Unspecified", value: 0 },
        { name: "Hair", value: 1 },
        { name: "Plant", value: 2 },
        { name: "Quills", value: 3 },
        { name: "Feathers", value: 4 },
        { name: "Goo", value: 5 },
        { name: "Tentacles", value: 6 },
        { name: "Transparent", value: 7 }
    ],
    Cup: [
        { name: "flat", value: 0 },
        { name: "A", value: 1 },
        { name: "B", value: 2 },
        { name: "C", value: 3 },
        { name: "D", value: 4 },
        { name: "DD", value: 5 },
        { name: "E", value: 6 },
        { name: "EE", value: 7 },
        { name: "F", value: 8 },
        { name: "FF", value: 9 },
        { name: "G", value: 10 },
        { name: "GG", value: 11 },
        { name: "H", value: 12 },
        { name: "HH", value: 13 },
        { name: "I", value: 14 },
        { name: "II", value: 15 },
        { name: "J", value: 16 },
        { name: "JJ", value: 17 },
        { name: "K", value: 18 },
        { name: "KK", value: 19 },
        { name: "L", value: 20 },
        { name: "LL", value: 21 },
        { name: "M", value: 22 },
        { name: "MM", value: 23 },
        { name: "N", value: 24 },
        { name: "NN", value: 25 },
        { name: "O", value: 26 },
        { name: "OO", value: 27 },
        { name: "P", value: 28 },
        { name: "PP", value: 29 },
        { name: "Q", value: 30 },
        { name: "QQ", value: 31 },
        { name: "R", value: 32 },
        { name: "RR", value: 33 },
        { name: "S", value: 34 },
        { name: "SS", value: 35 },
        { name: "T", value: 36 },
        { name: "TT", value: 37 },
        { name: "U", value: 38 },
        { name: "UU", value: 39 },
        { name: "V", value: 40 },
        { name: "VV", value: 41 },
        { name: "W", value: 42 },
        { name: "WW", value: 43 },
        { name: "X", value: 44 },
        { name: "XX", value: 45 },
        { name: "Y", value: 46 },
        { name: "YY", value: 47 },
        { name: "Z", value: 48 },
        { name: "ZZ", value: 49 }
    ],
    Weapons: [
        { name: "Walking Staff", value: "CaitsStaff" },
        { name: "Gnarled Staff", value: "GnarledStaff" },
        { name: "Aronas Mastbreaker", value: "AronasMastbreaker" },
        { name: "Summoned Halberd", value: "SummonedHalberd" },
        { name: "Fist", value: "Fist" },
        { name: "Rusty Knife", value: "RustyKnife" },
        { name: "Dagger", value: "Dagger" },
        { name: "Throwing Knife", value: "ThrowingKnife" },
        { name: "Short Sword", value: "ShortSword" },
        { name: "Curved Blade", value: "CurvedBlade" },
        { name: "Spear", value: "Spear" },
        { name: "Pike", value: "Pike" },
        { name: "Poleaxe", value: "Poleaxe" },
        { name: "Battleaxe", value: "Battleaxe" },
        { name: "Francisca", value: "Francisca" },
        { name: "Javelin", value: "Javelin" },
        { name: "Quarterstaff", value: "Quarterstaff" },
        { name: "Sling-staff", value: "SlingStaff" },
        { name: "Blade Staff", value: "BladeStaff" },
        { name: "Eternal Delusion", value: "EternalDelusion" },
        { name: "Seasonal Rhapsody", value: "SeasonalRhapsody" },
        { name: "Divine Blossom", value: "DivineBlossom" },
        { name: "Embodiment Of Law", value: "KiyokosScroll" },
        { name: "Hunting Bow", value: "HuntingBow" },
        { name: "Holy Hunting Bow", value: "HolyHuntingBow" },
        { name: "Ranger Bow", value: "RangerBow" },
        { name: "War Bow", value: "WarBow" },
        { name: "Sling", value: "Sling" },
        { name: "Mace", value: "Mace" },
        { name: "Mastbreaker", value: "Mastbreaker" },
        { name: "Nightfang", value: "Nightfang" },
        { name: "Beast Killer", value: "BeastKiller" },
        { name: "Sanctified Gladius", value: "SanctifiedGladius" },
        { name: "Spiraled Staff", value: "SpiraledStaff" },
        { name: "Spiraled Blade", value: "SpiraledBlade" },
        { name: "Salamander Spellblade", value: "SalamanderSpellblade" },
        { name: "Birch Staff", value: "BirchStaff" },
        { name: "Whitewood Bow", value: "WhitewoodBow" },
        { name: "Taeleeran Longbow", value: "TaeleeranLongbow" },
        { name: "Belharan Claymore", value: "BelharanClaymore" },
        { name: "Girthy Rod", value: "GirthyRod" },
        { name: "Metal Wand", value: "MetalWand" },
        { name: "Silver Cestus", value: "SilverCestus" },
        { name: "Galon's Griefmaker", value: "GalonsGriefmaker" },
        { name: "Bessy Mauler", value: "BessyMauler" },
        { name: "War Pick", value: "WarPick" },
        { name: "Flaming Dagger", value: "FlamingDagger" },
        { name: "Aphrodisiac Whip", value: "AphrodisiacWhip" },
        { name: "Sharp Sickle", value: "SharpSickle" },
        { name: "Balanced Blade", value: "BalancedBlade" },
        { name: "Kunai", value: "Kunai" },
        { name: "Straight Pike", value: "StraightPike" },
        { name: "Swift Sword", value: "SwiftSword" },
        { name: "Royal Greatspear", value: "RoyalGreatspear" },
        { name: "Captain's Greatsword", value: "CaptainsGreatsword" },
        { name: "War Scythe", value: "WarScythe" },
        { name: "Runecleaver", value: "Runecleaver" },
        { name: "Ancient-Hewer", value: "AncientHewer" },
        { name: "Blight Tendril", value: "BlightTendril" },
        { name: "Hankyu", value: "Hankyu" },
        { name: "Naginata", value: "Naginata" },
        { name: "Control Rod", value: "ControlRod" },
        { name: "Mushroom Staff", value: "MushroomStaff" },
        { name: "Chrysanthemum Petal", value: "ChrysanthemumPetal" },
        { name: "Knightly Short-lance", value: "KnightlyShortLance" },
        { name: "Floral Short-lance", value: "FloralShortLance" },
        { name: "Conjured Flame", value: "ConjuredFlame" },
        { name: "Bone Seax", value: "BoneSeax" }
    ],
    ArmorSet: [
        { name: "Comfortable Clothes", value: "ComfortableClothes" },
        { name: "Scale Armor", value: "ScaleArmor" },
        { name: "Mail Cuirass", value: "MailCuirass" },
        { name: "Breastplate", value: "Breastplate" },
        { name: "Apprentice Robes", value: "ApprenticeRobes" },
        { name: "Leather Jerkin", value: "LeatherJerkin" },
        { name: "Leather Coat", value: "LeatherCoat" },
        { name: "Passion Priestess Garb", value: "PassionPriestessGarb" },
        { name: "Sun-Dancer' Silks", value: "SunDancerSilks" },
        { name: "Gifted Witch Garb", value: "GiftedWitchGarb" },
        { name: "Hexblade Leathers", value: "HexbladeLeathers" },
        { name: "Aronas Warhides", value: "AronasWarhides" },
        { name: "Spirit Totem Warhides", value: "SpiritTotemWarhides" },
        { name: "Warhides", value: "Warhides" },
        { name: "Loincloth And Guards", value: "LoinclothAndGuards" },
        {
            name: "Frost Loincloth And Guards",
            value: "FrostLoinclothAndGuards"
        },
        { name: "Pyromancer's Garb", value: "PyromancersGarb" },
        { name: "Mail Bikini", value: "MailBikini" },
        { name: "Summoner's Robes", value: "SummonersRobes" },
        { name: "Witch's Corset", value: "WitchsCorset" },
        { name: "Outrider's Leathers", value: "OutridersLeathers" },
        { name: "Princess Dress", value: "PrincessDress" },
        { name: "Sigil-bound Jerkin", value: "SigilBoundJerkin" },
        { name: "Lamellar Armour", value: "LamellarArmour" },
        { name: "Ex-cultist Coat", value: "CultistCoat" },
        { name: "Noble Yukata", value: "NobleYukata" },
        { name: "Cultist Robes", value: "CultistRobes" },
        { name: "Royal Leathers", value: "RoyalLeathers" },
        { name: "Kunoichi Bodysuit", value: "KunoichiOutfit" },
        { name: "Bondage Gear", value: "BondageGear" },
        { name: "Elegant Dress", value: "ElegantDress" },
        { name: "Field Clothes", value: "KinuFieldClothes" },
        { name: "Royal Kimono", value: "KinuRoyalKimono" },
        { name: "Chieftain's Bronze", value: "ChieftainBronze" },
        { name: "Dancer's Silks", value: "DancerSilks" },
        {
            name: "Blackened Bronze Chestpiece",
            value: "BlackenedBronzeChestpiece"
        },
        { name: "Pretty Pink Corset", value: "PrettyPinkCorset" },
        { name: "Dream-Plate", value: "DreamPlate" },
        { name: "Latex Bodysuit", value: "LatexBodysuit" },
        { name: "Fishnet Outfit", value: "FishnetOutfit" },
        { name: "Tiran Vestments", value: "TiranVestments" },
        { name: "Tiran Nun's Habit", value: "TiranNunHabit" },
        { name: "Tiran Paladin Chestplate", value: "TiranPaladinChestplate" }
    ],
    ItemHead: [
        { name: "Witch's Hat", value: "WitchsHat" },
        { name: "Dueling Hat", value: "DuelingHat" },
        { name: "Wide-brimmed Hat", value: "WideBrimmedHat" },
        { name: "Helm Of Heroes", value: "HelmOfHeroes" },
        { name: "Horned Helm", value: "HornedHelm" },
        { name: "Hoplon Helm", value: "HoplonHelm" },
        { name: "Kabuto", value: "Kabuto" },
        { name: "Everblossom Hood", value: "EverblossomHood" },
        { name: "Silver Mask", value: "SilverMask" },
        { name: "Lureling's Eye", value: "LurelingsEye" }
    ],
    ItemNeck: [
        { name: "Ward Amulet", value: "WardAmulet" },
        { name: "Amulet Of Transference", value: "AmuletOfTransference" },
        { name: "Amulet Of Union", value: "AmuletOfUnion" },
        { name: "Maidenshield", value: "Maidenshield" },
        { name: "Serpent Locket", value: "SerpentLocket" },
        { name: "Fox-Tail Charm", value: "FoxTailCharm" },
        { name: "Magatama", value: "Magatama" },
        { name: "Black Monkshood", value: "BlackMonkshood" },
        { name: "Fluffy Scarf", value: "FluffyScarf" },
        { name: "Cultist Charm", value: "CultistCharm" },
        { name: "Choker Of The Pain Slut", value: "PainSlutChoker" },
        { name: "Collar Of Submission", value: "SubbyCollar" }
    ],
    ItemShoulders: [
        { name: "Flame Cape", value: "FlameCape" },
        { name: "Priestess Cloak", value: "PriestessCloak" },
        { name: "Hirrud's Cloak", value: "HirrudsCloak" },
        { name: "Cloak Of Winter", value: "CloakOfWinter" },
        { name: "Leather Spaulders", value: "LeatherSpaulders" },
        { name: "Bronze Pauldrons", value: "BronzePauldrons" },
        { name: "Guard's Cape", value: "GuardsCape" },
        { name: "Seaweave Shaman's Cape", value: "SeaweaveShamanCape" }
    ],
    ItemHands: [
        { name: "Gauntlets", value: "Gauntlets" },
        { name: "Arm Guards", value: "ArmGuards" },
        { name: "Silver Bracelet", value: "SilverBracelets" },
        { name: "Arm-length Leather Gloves", value: "ArmLeatherGloves" },
        { name: "Royal Gloves", value: "RoyalGloves" },
        { name: "Scaredy Cat Gloves", value: "CatGloves" },
        { name: "Gloves Of Giant Strength", value: "GiantsGloves" },
        { name: "Latex Gloves", value: "LatexGloves" }
    ],
    ItemWaist: [
        { name: "Potion Belt", value: "PotionBelt" },
        { name: "Hip Quiver", value: "HipQuiver" },
        { name: "Champion's Belt", value: "ChampionsBelt" },
        { name: "Sallow Belt", value: "SallowBelt" },
        { name: "Belt With A Pouch", value: "BeltWithPouch" },
        { name: "Leather Faulds", value: "LeatherFaulds" },
        { name: "Evergreen's Bountiful Bag", value: "EvergreensBountifulBag" },
        { name: "Fluffy Sash", value: "FluffySash" },
        { name: "Senninbari", value: "Senninbari" },
        { name: "Bottom Heavy Belt", value: "BottomHeavyBelt" },
        { name: "Tome Holster", value: "TomeHolster" }
    ],
    ItemFeet: [
        { name: "Iron Greaves", value: "IronGreaves" },
        { name: "Leather Boots", value: "LeatherBoots" },
        { name: "Cait's Knee Boots", value: "CaitsKneeBoots" },
        { name: "Thigh High Leather Boots", value: "ThighLeatherBoots" },
        { name: "Winged Sabatons", value: "WingedSabatons" },
        { name: "Iron Clogs", value: "IronClogs" },
        { name: "Kunoichi Footwear", value: "KunoichiFootwear" },
        { name: "Latex Boots", value: "LatexBoots" }
    ],
    Rings: [
        { name: "Wizard Ring", value: "WizardRing" },
        { name: "Rogue's Ring", value: "RoguesRing" },
        { name: "Ring Of Pure Thought", value: "RingOfPureThought" },
        { name: "Ring Of Temptation", value: "RingOfTemptation" },
        { name: "Mare's Ring", value: "MaresRing" },
        { name: "Hornet Ring", value: "HornetRing" },
        { name: "Lucky Strike", value: "LuckyStrike" },
        { name: "Charm", value: "Charm" },
        { name: "Kaneituuhou", value: "Kaneituuhou" }
    ],
    TopGarb: [
        { name: "Lacey Bra", value: "LaceyBra" },
        { name: "Silk Shirt", value: "SilkShirt" },
        { name: "Camisole", value: "Camisole" },
        { name: "Silk Corset", value: "SilkCorset" },
        { name: "Linen Tunic", value: "LinenTunic" },
        { name: "Black Seaweave Bra", value: "BlackSeaweaveBra" },
        { name: "Pink Seaweave Bra", value: "PinkSeaweaveBra" },
        { name: "Latex Bra", value: "LatexBra" },
        { name: "Cowprint Bra", value: "CowprintBra" }
    ],
    BottomGarb: [
        { name: "Plain Underwear", value: "PlainUnderwear" },
        { name: "Silk Panties", value: "SilkPanties" },
        { name: "Silk Thong", value: "SilkThong" },
        { name: "Stockings And Garterbelt", value: "Stockings" },
        { name: "Studded Leathers", value: "StuddedLeathers" },
        { name: "Seaweave Boyshorts", value: "SeaweaveBoyshorts" },
        { name: "Slutty Seaweave Panties", value: "SluttySeaweavePanties" },
        { name: "Pink Seaweave Thong", value: "PinkSeaweaveThong" },
        { name: "Latex Panties", value: "LatexPanties" },
        { name: "Latex Shorts", value: "LatexShorts" },
        { name: "Cowprint Panties", value: "CowprintPanties" }
    ],
    Offhand: [
        { name: "Hoplon Shield", value: "HoplonShield" },
        { name: "Blackwood Shield", value: "BlackwoodShield" },
        { name: "Beautiful Shield", value: "BeautifulShield" },
        { name: "Tower Shield", value: "TowerShield" },
        { name: "Wicker Shield", value: "WickerShield" },
        { name: "Runic Shield", value: "RunicShield" },
        { name: "Rosebloom Shield", value: "RosebloomShield" },
        { name: "Shield Of Brawn", value: "BrawnShield" },
        { name: "Winter Knight Shield", value: "WinterKnightShield" },
        { name: "Shield Orb", value: "ShieldOrb" },
        { name: "Lynx Totem", value: "LynxTotem" },
        { name: "Mage Wand", value: "MageWand" },
        { name: "War Totem", value: "WarTotem" },
        { name: "Blank Scroll", value: "BlankScroll" },
        { name: "Fox Jewel", value: "FoxJewel" },
        { name: "Noble Harp", value: "NobleHarp" },
        { name: "Wooden Pipes", value: "WoodenPipes" }
    ],
    TFs: [
        {
            name: "Fox Berry",
            value: "FoxBerry",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Cat's Tongue Berry",
            value: "CatsTongueBerry",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Root Of Man",
            value: "RootOfMan",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Pink Egg",
            value: "PinkEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Blue Egg",
            value: "BlueEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Blue Potion",
            value: "BluePotion",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Purple Egg",
            value: "PurpleEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Tan Egg",
            value: "TanEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Gold Egg",
            value: "GoldEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Brute Beet",
            value: "BruteBeet",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Glowing Ice Shard",
            value: "IceShard",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Minoblood Wine",
            value: "MinoBloodwine",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Bovum Sherry",
            value: "BovumSherry",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Baad Clover",
            value: "BaadClover",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Carrot Cumpcake",
            value: "CarrotCumpcake",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Manticore Nip",
            value: "ManticoreNip",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Virility Booster",
            value: "VirilityBooster",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Cackle Berry",
            value: "CackleBerry",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Lycanthorn",
            value: "Lycanthorn",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Wolfsboon",
            value: "Wolfsboon",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Cinderleaf",
            value: "Cinderleaf",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Frostleaf",
            value: "Frostleaf",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Grottato",
            value: "Grottato",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Ring Peach",
            value: "RingPeach",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Glitter Dust",
            value: "GlitterDust",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Belharan Stew",
            value: "BelharanStew",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Wyld Wine",
            value: "WyldWine",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Mare's Barley",
            value: "MareBarley",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Milk Candy",
            value: "MilkCandy",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Milk Tea",
            value: "MilkTea",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Double Pepper",
            value: "DoublePepper",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Knotted Pepper",
            value: "KnottedPepper",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Spider Silk",
            value: "SpiderSilk",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Pink Truffle",
            value: "PinkTruffle",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Leothran Herb",
            value: "LeoHerb",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Titan's Tangy Tea",
            value: "TitanTea",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Short Stack Stew",
            value: "ShortStew",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Gaia Leaflets",
            value: "GaiaLeaf",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Bimbo Brew",
            value: "BimboBrew",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Ice Rose",
            value: "IceRose",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Ursus Bulb",
            value: "UrsusBulb",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Wild Chicory",
            value: "WildChicory",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Catnip Tea",
            value: "CatnipTea",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Siorc Bulbs",
            value: "SiorcBulb",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Scale Salve",
            value: "ScaleSalve",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Blackened Herb",
            value: "BlackenedHerb",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Discolored Egg",
            value: "DiscoloredEgg",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Twisted Reed",
            value: "TwistedReed",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Hornet Sting",
            value: "HornetSting",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Succubus Milk",
            value: "SuccubusMilk",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Incubus Cum",
            value: "IncubusCum",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Tainted Clover",
            value: "TaintedClover",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        },
        {
            name: "Ashen Leaf",
            value: "AshenLeaf",
            attr: { "1": { text: "TF Type", type: "select", group: "TFType" } }
        }
    ],
    Misc: [
        { name: "Camping Supplies", value: "CampingSupplies" },
        { name: "Silver Sphere", value: "SilverSphere" },
        { name: "Small Silver Sphere", value: "SmallSilverSphere" },
        { name: "Large Silver Sphere", value: "LargeSilverSphere" },
        { name: "Pristine Wood", value: "PristineWood" },
        { name: "Broken Metal Parts", value: "MetalParts" },
        { name: "Sturdy Stone", value: "SturdyStone" },
        { name: "Mysterious Note", value: "MysteriousNote" },
        { name: "Undefined Lenses", value: "Lenses" },
        { name: "Undefined Scrub", value: "FurScrub" },
        { name: "Growth Stopper Scrub", value: "GrowthStopper" },
        { name: "Hair Growth Potion", value: "HairGrowthPotion" },
        { name: "Beard Growth Potion", value: "BeardGrowthPotion" },
        { name: "Get Good Facial-Scrub", value: "FacialScrub" },
        { name: "Ashenstone", value: "Ashenstone" },
        { name: "Emberstone", value: "Emberstone" },
        { name: "Blazingstone", value: "Blazingstone" },
        { name: "Weapons Crate", value: "WeaponsCrate" },
        { name: "Lyric", value: "Lyric" }
    ],
    Consumable: [
        { name: "Effigy Seed", value: "EffigySeed" },
        { name: "Wyvern Venom", value: "WyvernVenom" },
        { name: "Ovilixer", value: "Ovilixer" },
        { name: "Brown Leaf", value: "BrownLeaf" },
        { name: "Blank Powder", value: "BlankPowder" },
        { name: "Blood Iris", value: "BloodIris" },
        { name: "Fresh Milk", value: "FreshMilk" },
        { name: "Creamy Cheddar", value: "CreamyCheddar" },
        { name: "Bacon Strips", value: "BaconStrips" },
        { name: "Pupper Pale Ale", value: "PupperPaleAle" },
        { name: "Brazenberry Ale", value: "BrazenberryAle" },
        { name: "Conjurer's Concoction", value: "ConjurersConcoction" },
        { name: "Leananstone", value: "Leananstone" },
        { name: "Naptha", value: "Naptha" },
        { name: "Steadfast Tonic", value: "SteadfastTonic" },
        { name: "Oil Of Oliban", value: "OilOfOliban" },
        { name: "Remedy", value: "Remedy" },
        { name: "Vulnerary", value: "Vulnerary" },
        { name: "Winterstem", value: "Winterstem" },
        { name: "Trail Rations", value: "TrailRations" },
        { name: "Kaelirra's Tears", value: "KaelirrasTears" },
        { name: "Razorcup Nectar", value: "RazorcupNectar" },
        { name: "Ley-crystal Grenade", value: "LeyCrystalGrenade" },
        { name: "Frozen Kobold", value: "FrozenKobold" },
        { name: "Wyldsap", value: "Wyldsap" },
        { name: "Tome Of Disarm", value: "TomeOfDisarm" },
        { name: "Hornet Honey", value: "HornetHoney" },
        { name: "Red Cow Wine", value: "RedCowWine" },
        { name: "Kitsune Gift", value: "KitsuneGift" },
        { name: "Lustful Liquor", value: "LustfulLiquor" },
        { name: "Ice Wine", value: "IceWine" },
        { name: "Tome Of Arc Cannon", value: "TomeOfArcCannon" },
        { name: "Tome Of Kiaijutsu", value: "TomeOfKiaijutsu" },
        { name: "Tome Of Carnal Hex", value: "TomeOfCarnalHex" },
        { name: "Tome Of Counterspell", value: "TomeOfCounterspell" },
        { name: "Tome Of Heat Weapon", value: "TomeOfHeatWeapon" },
        { name: "Tome Of Leech", value: "TomeOfLeech" },
        { name: "Bento Box", value: "BentoBox" },
        { name: "Tome Of Vitality Reap", value: "TomeOfVitalityReap" },
        { name: "Tome Of Driving Thrust", value: "TomeOfDrivingThrust" },
        { name: "Tome Of Bark Skin", value: "TomeOfBarkSkin" },
        { name: "Tome Of Celestial Smite", value: "TomeOfCelestialSmite" },
        { name: "Tome Of Smite Evil", value: "TomeOfSmiteEvil" },
        { name: "Tome Of Lay On Hands", value: "TomeOfLayOnHands" },
        { name: "Tome Of Jade Flame", value: "TomeOfJadeFlame" },
        { name: "Tome Of Power Wave", value: "TomeOfPowerWave" },
        { name: "Pink Draught", value: "PinkDraught" },
        { name: "Hornet Venom", value: "HornetVenom" }
    ],
    Set: [
        { name: "Passion Priestess Garb", value: "PassionSet" },
        { name: "Sun-Dancer's Silks", value: "SunDancer" },
        { name: "Witch Gear", value: "WitchGearSet" },
        { name: "Hexblade Leathers", value: "HexbladeLeatherSet" },
        { name: "Loin Set", value: "LoinSet" },
        { name: "Female Loin Set", value: "FemaleLoinSet" },
        { name: "Winter Knight Set", value: "WinterKnightSet" },
        { name: "Pyromancer's Cloth", value: "PyromancersCloth" },
        { name: "Summoner's Gear", value: "SummonerSet" },
        { name: "Ex-cultist Armor", value: "ExcultistSet" },
        { name: "Outrider's Gear", value: "OutriderSet" },
        { name: "Knight Set", value: "KnightSet" },
        { name: "Onmyodo", value: "Onmyodo" },
        { name: "Kitsune-Bi", value: "KitsuneBi" },
        { name: "Kami-no-Michi", value: "KamiNoMichi" },
        { name: "Queenly Raiment", value: "QueenlyRaiment" },
        { name: "Warhides", value: "WarhidesSet" },
        { name: "Berserker", value: "BerserkerSet" },
        { name: "Chieftain's Bronze", value: "ChieftainBronzeSet" },
        { name: "Spirit Totem", value: "SpiritTotemSet" },
        { name: "Hive Knight Set", value: "HiveKnightSet" },
        { name: "Honey Maiden's Dress", value: "HoneyMaidensDress" }
    ],
    KeyItems: [
        { name: "Blue Gemstone Stud", value: "BlueGemstoneStud" },
        { name: "Waystone Charm", value: "WaystoneCharm" },
        { name: "Berwyn's Panties", value: "BerwynsPanties" },
        { name: "Alchemist Kit", value: "AlchemistKit" },
        { name: "Basket Of Javelins", value: "BasketOfJavelins" },
        { name: "Disguise", value: "OrcDisguise" },
        { name: "Silver Mirror", value: "SilverMirror" },
        { name: "Rampart Key", value: "RampartKey" },
        { name: "Old Dented Pot", value: "DentedPot" },
        { name: "Tarnished Kettle", value: "TarnishedKettle" },
        { name: "Rusty Cauldron", value: "RustyCauldron" },
        { name: "Jarl's Medallion", value: "JarlMedallion" },
        { name: "Ragnild's New Clothes", value: "RagsDress" },
        { name: "Honey Core", value: "HoneyCore" },
        { name: "Honey Key", value: "HoneyKey" },
        { name: "Venom Key", value: "VenomKey" },
        { name: "Nice Wine", value: "NiceWine" },
        { name: "Maid Costume", value: "MaidCostume" },
        { name: "Evergreen's Bountiful Bag", value: "EvergreensBountifulBag" },
        { name: "Promise Ring", value: "PromiseRing" },
        { name: "Jael'yn's Cock Ring", value: "JaelynsCockRing" },
        { name: "Cock Scepter", value: "CockScepter" },
        { name: "Dryad Seeds", value: "DryadSeeds" },
        { name: "Dildo", value: "Dildo" },
        { name: "Magic Anal Beads", value: "MagicalAnalBeads" },
        { name: "Buttplug", value: "Buttplug" },
        { name: "Shard Of Ice", value: "ShardOfIce" },
        { name: "Circlet Of Sunlight", value: "CircletOfSunlight" },
        { name: "Proposal Flower", value: "ProposalFlower" },
        { name: "Dire Wolf Corpse", value: "DireWolfCorpse" },
        { name: "Summoning Book", value: "SummoningBook" },
        { name: "Ghostlight Piercing", value: "GhostlightPiercing" },
        { name: "Lactic Studs", value: "LacticStuds" },
        { name: "Ornate Lantern", value: "Lantern" },
        { name: "Lethicite Shard", value: "LethiciteShard" }
    ],
    Boon: [
        { name: "Velun's Blessing", value: "VelunsBlessing" },
        { name: "Fountain's Bounty", value: "FountainsBounty" },
        { name: "Honey Mead", value: "HoneyMead" },
        { name: "Taurus Mead", value: "TaurusMead" },
        { name: "Spiced Wine", value: "SpicedWine" },
        { name: "Infused Milk", value: "InfusedMilk" },
        { name: "Rye Beer", value: "RyeBeer" },
        { name: "Apple Cider", value: "AppleCider" },
        { name: "Minoan Sherry", value: "MinoanSherry" },
        { name: "Monastery Ale", value: "MonasteryAle" },
        { name: "Winterberry Wine", value: "WinterberryWine" },
        { name: "Dragon's Ale", value: "DragonsAle" },
        { name: "Bento Box", value: "BentoBox" },
        { name: "Lover's Dry", value: "LoversDry" },
        { name: "Pale Ale", value: "PaleAle" },
        { name: "Total Purity", value: "TotalPurity" },
        { name: "Frostmander's Embrace", value: "FrostmandersEmbrace" },
        { name: "Blessing — Learning", value: "BlessingLearning" },
        { name: "Blessing — Health", value: "BlessingHealth" },
        { name: "Blessing — Romance", value: "BlessingRomance" },
        { name: "Blessing — Ritual Purity", value: "BlessingPurity" },
        { name: "Blessing — Wealth", value: "BlessingWealth" },
        { name: "Physical Massage", value: "PhysicalMassage" },
        { name: "Elemental Massage", value: "ElementalMassage" },
        { name: "Spiritual Massage", value: "SpiritualMassage" },
        { name: "Mental Massage", value: "MentalMassage" },
        { name: "Good Fortune", value: "GoodFortune" },
        { name: "Bad Fortune", value: "BadFortune" }
    ],
    StatusEffect: [
        { name: "Anally Filled", value: "AnallyFilled" },
        { name: "Orally Filled", value: "OrallyFilled" },
        { name: "Vaginally Filled", value: "VaginallyFilled" },
        { name: "Armorer", value: "Armorer" },
        { name: "Sharpen Blades", value: "SharpenBlades" },
        { name: "Prayer Of Warding", value: "PrayerOfWarding" },
        { name: "Arcane Infusion", value: "ArcaneInfusion" },
        { name: "Arcane Attunement", value: "ArcaneAttunement" },
        { name: "Heart's Desires", value: "HeartsDesires" },
        { name: "Focusing Performance", value: "FocusingPerformance" },
        { name: "Take Comfort In Me", value: "TakeComfort" },
        { name: "Hive Knight's Scent", value: "HiveKnightsScent" },
        { name: "Cherish This", value: "CherishThis" },
        { name: "Omikuji", value: "Omikuji" },
        { name: "War Paint", value: "WarPaint" },
        { name: "Eye Of The Storm", value: "EyeOfTheStorm" },
        { name: "Ranger's Quarry", value: "RangersQuarry" },
        { name: "Enervation", value: "Enervation" },
        { name: "Aphrodisiac Covered", value: "AphrodisiacCovered" },
        { name: "Well Fed", value: "WellFed" },
        { name: "Blue Balled", value: "BlueBalled" },
        { name: "Relaxed", value: "Relaxed" },
        { name: "Venom High", value: "VenomHigh" },
        { name: "Fatigued", value: "Fatigued" },
        { name: "Bruised And Beaten", value: "BruisedAndBeaten" },
        { name: "Happy Tummy", value: "HappyTummy" },
        { name: "Overburdened", value: "Overburdened" },
        { name: "Heat", value: "Heat" },
        { name: "Artificial Heat", value: "ArtificialHeat" },
        { name: "Rut", value: "Rut" },
        { name: "Artificial Rut", value: "ArtificialRut" },
        { name: "Temporary Infertility", value: "TemporaryInfertility" },
        { name: "Temporary Sterility", value: "TemporarySterility" },
        { name: "Stud Statue's Gift", value: "StudStatuesGift" },
        { name: "Matron Statue's Gift", value: "MatronStatuesGift" },
        { name: "Cum Covered", value: "CumCovered" },
        { name: "Milk Bathed", value: "MilkBathed" },
        { name: "Drained", value: "Drained" },
        { name: "Honey Brain", value: "HoneyBrain" },
        { name: "Dark Devotion", value: "DarkDevotion" },
        { name: "Unstable Presence", value: "UnstablePresence" },
        { name: "Hornet High", value: "HornetHigh" },
        { name: "Venom Withdrawal", value: "VenomWithdrawal" },
        { name: "Venom Craving", value: "VenomCraving" },
        { name: "Weakened", value: "Weakened" }
    ],
    CombatEffect: [
        { name: "Prone", value: "Prone" },
        { name: "Bleeding", value: "Bleeding" },
        { name: "Sundered", value: "Sundered" },
        { name: "Enamored", value: "Enamored" },
        { name: "Obscured", value: "Obscured" },
        { name: "Staggered", value: "Staggered" },
        { name: "Burning", value: "Burning" },
        { name: "Terrified", value: "Terrified" },
        { name: "Poisoned", value: "Poisoned" },
        { name: "Frigid", value: "Frigid" },
        { name: "Stunned", value: "Stunned" },
        { name: "Stun/Prone Immune", value: "StunImmune" },
        { name: "Aroused", value: "Aroused" },
        { name: "Lust Tagged", value: "LustTagged" },
        { name: "Disarmed", value: "Disarmed" },
        { name: "Silenced", value: "Silenced" },
        { name: "Blinded", value: "Blinded" },
        { name: "Blessed", value: "Blessed" },
        { name: "Spirit Veil", value: "SpiritVeil" },
        { name: "Mirror Image", value: "MirrorImage" },
        { name: "Rhythmic Focus", value: "RhythmicFocus" },
        { name: "Resistance", value: "Resistance" },
        { name: "Weapon Buff", value: "WeaponBuff" },
        { name: "Feather Dance", value: "FeatherDance" },
        { name: "Warlord's Cry", value: "WarlordsCry" },
        { name: "Tainted Bulwark", value: "TaintedBulwark" },
        { name: "First Strike", value: "FirstStrike" },
        { name: "Focused", value: "Focused" },
        { name: "Covered", value: "Covered" },
        { name: "Bolstered", value: "Bolstered" },
        { name: "Protected", value: "Protected" },
        { name: "Shielded", value: "Shielded" },
        { name: "Restrained", value: "Restrained" },
        { name: "Bloodlust", value: "Bloodlust" },
        { name: "Heightened Senses", value: "HeightenedSenses" },
        { name: "Vanguard", value: "Vanguard" },
        { name: "Shield Of Light", value: "ShieldOfLight" },
        { name: "Song Of Splendor", value: "SongOfSplendor" },
        { name: "Song Of Courage", value: "SongOfCourage" },
        { name: "Brazenberry Ale", value: "BrazenberryAle" },
        { name: "Conjurer's Concoction", value: "ConjurersConcoction" },
        { name: "Steadfast Tonic", value: "SteadfastTonic" },
        { name: "Winterstem", value: "Winterstem" },
        { name: "Ancestral Aegis", value: "AncestralAegis" },
        { name: "Eternal Light", value: "EternalLight" },
        { name: "Everblossom Hood", value: "EverblossomHood" },
        { name: "Holy Ward", value: "HolyWard" },
        { name: "Counterspelled", value: "Counterspelled" },
        { name: "Banished", value: "Banished" },
        { name: "Inspired", value: "Inspired" },
        { name: "Unbreakable", value: "Unbreakable" },
        { name: "Floral Aegis", value: "FloralAegis" },
        { name: "Sweet Protector", value: "SweetProtector" },
        { name: "Spirit Bound", value: "SpiritBound" },
        { name: "Shelled", value: "Shelled" },
        { name: "Ancestor's Judgement", value: "AncestorsJudgement" },
        { name: "Defending", value: "Defending" },
        { name: "Blade Block", value: "BladeBlock" },
        { name: "Overcharge", value: "Overcharged" },
        { name: "Curse Of Misfortune", value: "CurseOfMisfortune" },
        { name: "Immolation", value: "Immolation" },
        { name: "Karmic Retribution", value: "KarmicRetribution" },
        { name: "Enraging Challenge", value: "EnragingChallenge" },
        { name: "Bark Skin", value: "BarkSkin" },
        { name: "Distracted", value: "Distracted" },
        { name: "Fairy Ring", value: "FairyRing" },
        { name: "Blur", value: "Blur" },
        { name: "Baffled", value: "Baffled" }
    ],
    Powers: [
        { name: "Base Tease", value: "BaseTease" },
        { name: "Ass Tease", value: "AssTease" },
        { name: "Crotch Tease", value: "CrotchTease" },
        { name: "Chest Tease", value: "ChestTease" },
        { name: "Allure", value: "Allure" },
        { name: "Feather Dance", value: "FeatherDance" },
        { name: "Sun Dance", value: "SunDance" },
        { name: "Chainmail Jiggle", value: "ChainmailJiggle" },
        { name: "Breast Plate", value: "BreastPlate" },
        { name: "Cum Spray", value: "CumSpray" },
        { name: "Lust Tag", value: "LustTag" },
        { name: "Enamoring", value: "Enamoring" },
        { name: "Wyvern Venom", value: "WyvernVenom" },
        { name: "Honey Slather", value: "HoneySlather" },
        { name: "Aphrodisiac Sting", value: "AphrodisiacSting" },
        { name: "Mind Snap", value: "MindSnap" },
        { name: "One-Two", value: "OneTwo" },
        { name: "Spider's Stride", value: "SpidersStride" },
        { name: "Lust Tail", value: "LunchTime" },
        { name: "Defend", value: "Defend" },
        { name: "Guarded Stance", value: "GuardedStance" },
        { name: "Shielded Stance", value: "ShieldedStance" },
        { name: "Protect", value: "Protect" },
        { name: "Ranger's Stance", value: "RangersStance" },
        { name: "Duelist's Stance", value: "DuelistsStance" },
        { name: "Mirror Stance", value: "MirrorStance" },
        { name: "Charge Weapon", value: "ChargeWeapon" },
        { name: "Frozen Edge", value: "FrozenEdge" },
        { name: "Rhythmic Focus", value: "RhythmicFocus" },
        { name: "Spirit Veil", value: "SpiritVeil" },
        { name: "Mirror Image", value: "MirrorImage" },
        { name: "Holy Ward", value: "HolyWard" },
        { name: "Control Pheromones", value: "ControlPheromones" },
        { name: "Bolstering Dance", value: "BolsteringDance" },
        { name: "Firewalk", value: "Firewalk" },
        { name: "Song Of Courage", value: "SongOfCourage" },
        { name: "Flight", value: "Flight" },
        { name: "Frenzy", value: "Frenzy" },
        { name: "Equanimity", value: "Equanimity" },
        { name: "Intuition", value: "Intuition" },
        { name: "Equilibrium", value: "Equilibrium" },
        { name: "Tranquility", value: "Tranquility" },
        { name: "Aura Of Desire", value: "AuraOfDesire" },
        { name: "Piper's Song", value: "PipersSong" },
        { name: "Vine Restraints", value: "VineRestraints" },
        { name: "Harpy Song", value: "HarpySong" },
        { name: "Pollination", value: "Pollination" },
        { name: "Heal", value: "Heal" },
        { name: "Lay On Hands", value: "LayOnHands" },
        { name: "Great Heal", value: "GreatHeal" },
        { name: "Group Heal", value: "GroupHeal" },
        { name: "Cleansing Bell", value: "CleansingBell" },
        { name: "Guidance", value: "Guidance" },
        { name: "Command Pheromones", value: "CommandPheromones" },
        { name: "Warlord's Cry", value: "WarlordsCry" },
        { name: "Mega-Heal", value: "MegaHeal" },
        { name: "Smoke Bomb", value: "SmokeBomb" },
        { name: "Pocket Sand", value: "PocketSand" },
        { name: "Tainted Bulwark", value: "TaintedBulwark" },
        { name: "Blessing", value: "Blessing" },
        { name: "Grease", value: "Grease" },
        { name: "Song Of Storms", value: "SongOfStorms" },
        { name: "Blinding Beauty", value: "BlindingBeauty" },
        { name: "Tentacle Shield", value: "TentacleShield" },
        { name: "Kiaijutsu", value: "Kiaijutsu" },
        { name: "Counterspell", value: "Counterspell" },
        { name: "Warcry", value: "Warcry" },
        { name: "Raging Thurible", value: "RagingThurible" },
        { name: "War Song", value: "WarSong" },
        { name: "Vanguard", value: "Vanguard" },
        { name: "Ancestral Aegis", value: "AncestralAegis" },
        { name: "Shield Of Light", value: "ShieldOfLight" },
        { name: "Soothing Dance", value: "SoothingDance" },
        { name: "Eternal Light", value: "EternalLight" },
        { name: "Song Of Splendor", value: "SongOfSplendor" },
        { name: "Blood Iris", value: "BloodIris" },
        { name: "Brazenberry Ale", value: "BrazenberryAle" },
        { name: "Conjurer's Concoction", value: "ConjurersConcoction" },
        { name: "Naptha", value: "Naptha" },
        { name: "Steadfast Tonic", value: "SteadfastTonic" },
        { name: "Oil Of Oliban", value: "OilOfOliban" },
        { name: "Remedy", value: "Remedy" },
        { name: "Vulnerary", value: "Vulnerary" },
        { name: "Winterstem", value: "Winterstem" },
        { name: "Kaelirra's Tears", value: "KaelirrasTears" },
        { name: "Ley Crystal Grenade", value: "LeyCrystalGrenade" },
        { name: "Throw Lyric", value: "LyricThrow" },
        { name: "Wyldsap", value: "Wyldsap" },
        { name: "Hornet Honey", value: "HornetHoney" },
        { name: "Hornet Venom", value: "HornetVenom" },
        { name: "Inspiration", value: "Inspiration" },
        { name: "Unbreakable", value: "Unbreakable" },
        { name: "Floral Aegis", value: "FloralAegis" },
        { name: "Sweet Protector", value: "SweetProtector" },
        { name: "Revive", value: "Revive" },
        { name: "Devotion", value: "Devotion" },
        { name: "Spirit Binder", value: "SpiritBinder" },
        { name: "Shell", value: "Shell" },
        { name: "Overcharge", value: "Overcharge" },
        { name: "Detonate", value: "Detonate" },
        { name: "Calm Mind", value: "CalmMind" },
        { name: "Komari Kitsunetsuki", value: "KomariKitsunetsuki" },
        { name: "Kitsunetsuki", value: "Kitsunetsuki" },
        { name: "Life-Bond", value: "LifeBond" },
        { name: "Karmic Retribution", value: "KarmicRetribution" },
        { name: "Infernal Bond", value: "InfernalBond" },
        { name: "Enraging Challenge", value: "EnragingChallenge" },
        { name: "Wraith Touch", value: "WraithTouch" },
        { name: "Bark Skin", value: "BarkSkin" },
        { name: "Berserkergang", value: "Berserkergang" },
        { name: "Acid Flask", value: "AcidFlask" },
        { name: "Estrus Flask", value: "EstrusFlask" },
        { name: "Fairy Ring", value: "FairyRing" },
        { name: "Kamikaze", value: "Kamikaze" },
        { name: "Banshee Wail", value: "BansheeWail" },
        { name: "Resplendent Aria", value: "ResplendentAria" },
        { name: "Take Cover", value: "TakeCover" },
        { name: "Prestidigitation", value: "Prestidigitation" },
        { name: "Punch", value: "Punch" },
        { name: "Butt Stomp", value: "ButtStomp" },
        { name: "Aerial Drop", value: "AerialDrop" },
        { name: "Quake", value: "Quake" },
        { name: "Rush", value: "Rush" },
        { name: "Grapple", value: "Grapple" },
        { name: "Tackle", value: "Tackle" },
        { name: "Chain Whip", value: "ChainWhip" },
        { name: "Trample", value: "Trample" },
        { name: "Shield Bash", value: "ShieldBash" },
        { name: "War Stomp", value: "WarStomp" },
        { name: "Charge", value: "Charge" },
        { name: "Centaur Trample", value: "CentaurTrample" },
        { name: "Dominance", value: "AmazonStrike" },
        { name: "Garrote", value: "Garrote" },
        { name: "Influence", value: "Influence" },
        { name: "Exertion", value: "Exertion" },
        { name: "Overbear", value: "Overbear" },
        { name: "Bloodrage", value: "Bloodrage" },
        { name: "Tail Whack", value: "TailWhack" },
        { name: "Pummel Foe", value: "PummelFoe" },
        { name: "Boulder Heave", value: "BoulderHeave" },
        { name: "By The Horns", value: "ByTheHorns" },
        { name: "Lightning Fist", value: "LightningFist" },
        { name: "Stompy", value: "Stompy" },
        { name: "Bull Rush", value: "BullRush" },
        { name: "Bullrush", value: "Bullrush" },
        { name: "Fire Summon Attack", value: "FireSummonAttack" },
        { name: "Pussy Tail Tease", value: "PussyTailTease" },
        { name: "Harpy Butt Tease", value: "HarpyButtTease" },
        { name: "Effigy Boob Tease", value: "EffigyBoobTease" },
        { name: "Cultist's Allure", value: "CultistAllure" },
        { name: "Earth Fist", value: "EarthFist" },
        { name: "Tentacle Slap", value: "TentacleSlap" },
        { name: "Belly Dance", value: "BellyDance" },
        { name: "Dick Wobble", value: "DickWobble" },
        { name: "Imp Dirty Trick", value: "ImpDirtyTrick" },
        { name: "Tentacle Lash", value: "TentacleLash" },
        { name: "Merielle Chest", value: "MerielleChest" },
        { name: "Merielle Ass", value: "MerielleAss" },
        { name: "Merielle Crotch", value: "MerielleCrotch" },
        { name: "Fritte Chest", value: "FritteChest" },
        { name: "Fritte Ass", value: "FritteAss" },
        { name: "Fritte Crotch", value: "FritteCrotch" },
        { name: "Elaril Chest", value: "ElarilChest" },
        { name: "Elaril Crotch", value: "ElarilCrotch" },
        { name: "Manticore Tail", value: "ManticoreTail" },
        { name: "Jen Execute", value: "JenExecute" },
        { name: "Jen Thunder Strike", value: "JenThunderStrike" },
        { name: "Warg Claw", value: "WargClaw" },
        { name: "Mule Kick", value: "MuleKick" },
        { name: "Warg Trample", value: "WargTrample" },
        { name: "Bleeding Bite", value: "BleedingBite" },
        { name: "Spear Thrust", value: "SpearThrust" },
        { name: "Vaush Attack", value: "VaushAttack" },
        { name: "Healing Thurible", value: "HealingThurible" },
        { name: "Healing Howl", value: "HealingHowl" },
        { name: "Apprentice Attack", value: "ApprenticeAttack" },
        { name: "Slime Glomp", value: "SlimeGlomp" },
        { name: "Matiha Fireball", value: "MatihaFireball" },
        { name: "Zipping Harrassment", value: "ZippingHarrassment" },
        { name: "Magical Flash", value: "MagicalFlash" },
        { name: "Unintentional Tease", value: "UnintentionalTease" },
        { name: "Drider Prime Target", value: "DriderPrimeTarget" },
        { name: "Pincer Smash", value: "PincerSmash" },
        { name: "Honey Cum Spray", value: "HoneyCumSpray" },
        { name: "Harrick Blood Let", value: "HarrickBloodLet" },
        { name: "Jaelyn Attack", value: "JaelynAttack" },
        { name: "Lightbeams", value: "Lightbeams" },
        { name: "Ahmri Attack", value: "AhmriAttack" },
        { name: "Ahmri Kick", value: "AhmriKick" },
        { name: "Unitaur Shatter", value: "UnitaurShatter" },
        { name: "Behemoth Rend", value: "BehemothRend" },
        { name: "Behemoth Aerial Drop", value: "BehemothAerialDrop" },
        { name: "Inspire Wrath", value: "InspireWrath" },
        { name: "Mushroom Miasma", value: "MushroomMiasma" },
        { name: "Flaming Bull Attack", value: "FlamingBullAttack" },
        { name: "Lustful Images", value: "LustfulImages" },
        { name: "Blight Orb", value: "BlightOrb" },
        { name: "White Fire", value: "WhiteFire" },
        { name: "Withering Bolt", value: "WitheringBolt" },
        { name: "Lightning Spike", value: "LightningSpike" },
        { name: "Entropic Winds", value: "EntropicWinds" },
        { name: "Winter's Howl", value: "WintersHowl" },
        { name: "Wintery Bellow", value: "WinteryBellow" },
        { name: "Shadow Magic", value: "ShadowMagic" },
        { name: "Charm Spell", value: "CharmSpell" },
        { name: "Hypnotic Words", value: "HypnoticWords" },
        { name: "Sun Of Jassira", value: "SunOfJassira" },
        { name: "Fire Bolt", value: "FireBolt" },
        { name: "Pollen Spray", value: "PollenSpray" },
        { name: "Foxfire", value: "Foxfire" },
        { name: "Trick", value: "Trick" },
        { name: "Fireball", value: "Fireball" },
        { name: "Dark Thoughts", value: "DarkThoughts" },
        { name: "Leech", value: "Leech" },
        { name: "Carnal Hex", value: "CarnalHex" },
        { name: "Cold Snap", value: "ColdSnap" },
        { name: "Freeze Solid", value: "FreezeSolid" },
        { name: "Vile Miasma", value: "VileMiasma" },
        { name: "Jolt", value: "Jolt" },
        { name: "Groping Tentacles", value: "GropingTentacles" },
        { name: "Ray Of Frost", value: "RayOfFrost" },
        { name: "Soul Arrow", value: "SoulArrow" },
        { name: "Leananstone", value: "Leananstone" },
        { name: "Ancestor's Judgement", value: "AncestorsJudgement" },
        { name: "Shatter", value: "Shatter" },
        { name: "Devious Ruse", value: "DeviousRuse" },
        { name: "Heat Weapon", value: "HeatWeapon" },
        { name: "Will-o-Wisp", value: "WillOWisp" },
        { name: "Magic Missile", value: "MagicMissile" },
        { name: "Firewyrms", value: "Firewyrms" },
        { name: "Blue Flame Blade", value: "BlueFlameBlade" },
        { name: "Hex", value: "Hex" },
        { name: "Banishment", value: "Banishment" },
        { name: "Arc Cannon", value: "ArcCannon" },
        { name: "Mass Drain", value: "MassDrain" },
        { name: "Nullify", value: "Nullify" },
        { name: "Banish", value: "BanishSummon" },
        { name: "Entropic Fortune", value: "EntropicFortune" },
        { name: "Immolation", value: "Immolation" },
        { name: "Calamitous Seal", value: "CalamitousSeal" },
        { name: "Abyssal Miasma", value: "AbyssalMiasma" },
        { name: "Dragon's Breath", value: "DragonsBreath" },
        { name: "Vitality Reap", value: "VitalityReap" },
        { name: "Corruptive Blast", value: "CorruptiveBlast" },
        { name: "Psyshock", value: "Psyshock" },
        { name: "Celestial Smite", value: "CelestialSmite" },
        { name: "Primal Scar", value: "PrimalScar" },
        { name: "Psychic Blast", value: "PsychicBlast" },
        { name: "Dischord", value: "Dischord" },
        { name: "Dischordant", value: "Dischordant" },
        { name: "Grand Finale", value: "GrandFinale" },
        { name: "Flare", value: "Flare" },
        { name: "Jade Flame", value: "JadeFlame" },
        { name: "Baffle", value: "Baffle" },
        { name: "Frequency Adherence", value: "FrequencyAdherence" },
        { name: "Summon Flame Spirit", value: "SummonFlameSpirit" },
        { name: "Summon Golem", value: "SummonStoneElemental" },
        { name: "Summon Effigy", value: "SummonEffigy" },
        { name: "Summon Kiyoko", value: "SummonKiyoko" },
        { name: "Shadow Clone", value: "SummonShadowClone" },
        { name: "Call Falcon", value: "CallFalcon" },
        { name: "Merc Reinforcements", value: "MercReinforcements" },
        { name: "Summon Phyria", value: "SummonPhyria" },
        { name: "Mystic Call", value: "MysticCall" },
        { name: "Summon Hornets", value: "SummonHornets" },
        { name: "Summon Wolf Spirit", value: "SummonWolfSpirit" },
        { name: "Spew Elf", value: "SpewElf" },
        { name: "Spew Dragon", value: "SpewDragon" },
        { name: "Summon Sporeling", value: "SummonSporeling" },
        { name: "Summon Valkyrie", value: "SummonValkyrie" },
        { name: "Summon Bull", value: "SummonBull" },
        { name: "Summon Flame Dancer", value: "SummonFlameDancer" },
        { name: "Summon Flame Knight", value: "SummonFlameKnight" },
        { name: "Split Self", value: "SplitSelf" },
        { name: "Lureling's Song", value: "LurelingSong" },
        { name: "Normal Attack", value: "NormalAttack" },
        { name: "Rend", value: "Rend" },
        { name: "Fading Strike", value: "FadingStrike" },
        { name: "Sneak Attack", value: "SneakAttack" },
        { name: "Dirty Trick", value: "DirtyTrick" },
        { name: "Thunder Strike", value: "ThunderStrike" },
        { name: "Bleeding Cut", value: "BleedingCut" },
        { name: "Cleave", value: "Cleave" },
        { name: "Deadly Shadow", value: "DeadlyShadow" },
        { name: "Thunderous Sweep", value: "ThunderousSweep" },
        { name: "Wyvern Ignition", value: "WyvernIgnition" },
        { name: "Shell Cracker", value: "ShellCracker" },
        { name: "Shadow Strike", value: "ShadowStrike" },
        { name: "Precise Thrust", value: "PreciseThrust" },
        { name: "Mark For Death", value: "MarkForDeath" },
        { name: "Prime Target", value: "PrimeTarget" },
        { name: "Giant's Reach", value: "GiantsReach" },
        { name: "Execute", value: "Execute" },
        { name: "Lusty Tentacles", value: "LustyTentacles" },
        { name: "Envenom", value: "Envenom" },
        { name: "Trick Shot", value: "TrickShot" },
        { name: "Shatterstrike", value: "Shatterstrike" },
        { name: "Wyvern Sting", value: "WyvernSting" },
        { name: "Sun Arrow", value: "SunArrow" },
        { name: "Crowd Control", value: "CrowdControl" },
        { name: "Stick And Move", value: "StickAndMove" },
        { name: "Suppresive Fire", value: "SuppressiveFire" },
        { name: "Nerves Of Steel", value: "NervesOfSteel" },
        { name: "Triple Threat", value: "TripleThreat" },
        { name: "Crackle Powder", value: "CracklePowder" },
        { name: "Frost Arrow", value: "FrostArrow" },
        { name: "Blood Let", value: "BloodLet" },
        { name: "Enrage", value: "Enrage" },
        { name: "Fan Of Blades", value: "FanOfBlades" },
        { name: "Steady Strike", value: "SteadyStrike" },
        { name: "Dual Blitz", value: "DualBlitz" },
        { name: "Dastardly Trick", value: "DastardlyTrick" },
        { name: "Smite Evil", value: "SmiteEvil" },
        { name: "Poison Edge", value: "PoisonEdge" },
        { name: "Overhand Smash", value: "OverhandSmash" },
        { name: "Sure Shot", value: "SureShot" },
        { name: "Aim: Weapon", value: "AimWeapon" },
        { name: "Arcane Shot", value: "ArcaneShot" },
        { name: "Pummel", value: "Pummel" },
        { name: "Echoes Of Life", value: "EchoesOfLife" },
        { name: "Chill Touch", value: "ChillTouch" },
        { name: "Disarm", value: "Disarm" },
        { name: "Power Wave", value: "PowerWave" },
        { name: "Holy Shock", value: "HolyShock" },
        { name: "Assassinate", value: "Assassinate" },
        { name: "Aurora Arrow", value: "AuroraArrow" },
        { name: "Blade Block", value: "BladeBlock" },
        { name: "Driving Thrust", value: "DrivingThrust" },
        { name: "Driving Shot", value: "DrivingShot" },
        { name: "Double Attack", value: "DoubleAttack" },
        { name: "Lunge", value: "Lunge" },
        { name: "Chain Swing", value: "ChainSwing" },
        { name: "Wide Sweep", value: "WideSweep" },
        { name: "Get Over Here", value: "GetOverHere" },
        { name: "Eviscerate", value: "Eviscerate" },
        { name: "Pc Eviscerate", value: "pcEviscerate" },
        { name: "Eagle Eye", value: "EagleEye" },
        { name: "Frostfire Shot", value: "FrostfireShot" },
        { name: "Ground Pound", value: "GroundPound" },
        { name: "Echoing Assault", value: "EchoingAssault" }
    ],
    Perks: [
        { name: "Twist The Knife", value: "TwistTheKnife" },
        { name: "Sharpen Blades", value: "SharpenBlades" },
        { name: "Escape Artist", value: "EscapeArtist" },
        { name: "Veteran", value: "Veteran" },
        { name: "Armorer", value: "Armorer" },
        { name: "Iron Will", value: "IronWill" },
        { name: "Healer's Hands", value: "HealersHands" },
        { name: "Prayer Of Warding", value: "PrayerOfWarding" },
        { name: "Focused Will", value: "FocusedWill" },
        { name: "Arcane Infusion", value: "ArcaneInfusion" },
        { name: "Arcane Strike", value: "ArcaneStrike" },
        { name: "Arcane Attunement", value: "ArcaneAttunement" },
        { name: "Stylish!", value: "Stylish" },
        { name: "Focusing Performance", value: "FocusingPerformance" },
        { name: "Heart's Desires", value: "HeartsDesires" },
        { name: "Filthy Tease", value: "FilthyTease" },
        { name: "Commanding Presence", value: "CommandingPresense" },
        { name: "Dance Of The Dunes", value: "DanceOfDunes" },
        { name: "War Paint", value: "WarPaint" },
        { name: "Rending Strike", value: "RendingStrike" },
        { name: "Overbearing", value: "Overbearing" },
        { name: "Frenzy", value: "Frenzy" },
        { name: "Eye Of The Storm", value: "EyeOfTheStorm" },
        { name: "Journeyman Summoner", value: "JourneymanSummoner" },
        { name: "Ranger's Quarry", value: "RangersQuarry" },
        { name: "Take Comfort In Me", value: "TakeComfort" },
        { name: "Hive Knight's Scent", value: "HiveKnightsScent" },
        { name: "Cherish This", value: "CherishThis" },
        { name: "Cold Blooded", value: "ColdBlooded" },
        { name: "Imposing", value: "Imposing" },
        { name: "Embers", value: "Embers" },
        { name: "Omikuji", value: "Omikuji" },
        { name: "Slip Of The Mind", value: "SlipOfTheMind" },
        { name: "Countermagic", value: "Countermagic" },
        { name: "Second Sight", value: "SecondSight" },
        { name: "Dakini", value: "Dakini" },
        { name: "Starting Bonuses", value: "StartingAttributeBonuses" },
        { name: "Leftovers", value: "Leftovers" },
        { name: "Light Sensitivity", value: "LightSensitivity" },
        { name: "Font Of Will", value: "FontOfWill" },
        { name: "Horsey Heat", value: "HorseyHeat" },
        { name: "Medicae", value: "Medicae" },
        { name: "Archmage", value: "Archmage" },
        { name: "Immovable", value: "Immovable" },
        { name: "Arousing Aura", value: "ArousingAura" },
        { name: "Killing Spree", value: "KillingSpree" },
        { name: "Unburdened", value: "Unburdened" },
        { name: "Well Hung", value: "WellHung" },
        { name: "Buxom", value: "Buxom" },
        { name: "Stretchy", value: "Stretchy" },
        { name: "Size Queen", value: "SizeMonarch" },
        { name: "Breeder", value: "Breeder" },
        { name: "Sterile", value: "Sterile" },
        { name: "Milky", value: "Milky" },
        { name: "Libidinous", value: "Libidinous" },
        { name: "Reserved", value: "Reserved" },
        { name: "Messy Orgasm", value: "MessyOrgasm" },
        { name: "Bubble Butt", value: "BubbleButt" },
        { name: "Chastity", value: "Chastity" },
        { name: "Oviparous", value: "Oviparous" },
        { name: "Nuki Nuts", value: "NukiNuts" },
        { name: "Cum Cascades", value: "CumCascades" },
        { name: "Bimbo", value: "Bimbo" },
        { name: "Fertility+", value: "FertilityPlus" },
        { name: "Corrupted Libido", value: "CorruptedLibido" },
        { name: "Goblin Broodmare", value: "GoblinBroodmare" },
        { name: "Sex Goddess", value: "SexGoddess" },
        { name: "Corrupted Breeder", value: "CorruptedBreeder" },
        { name: "Corrupted Stud", value: "CorruptedStud" },
        { name: "Mega Milk", value: "MegaMilk" },
        { name: "Lubricated Pussy", value: "LubedPussy" },
        { name: "Nuts Half Full", value: "NutsHalfFull" },
        { name: "Soulbound", value: "Soulbound" },
        { name: "Champion's Resolve", value: "ChampionsResolve" }
    ]
} as const;
