export const Quests = [
    { name: "In Her Footsteps", comp: [6], fail: [], states: 7 },
    { name: "Right of Conquest", comp: [7, 8, 9], fail: [], states: 11 },
    { name: "Cat Call", comp: [3], fail: [], states: 6 },
    { name: "One Man's Poison", comp: [1], fail: [], states: 2 },
    { name: "Caparison Hunter", comp: [8], fail: [], states: 9 },
    { name: "The Mistress", comp: [2, 3], fail: [], states: 4 },
    { name: "Royal Amnesty", comp: [1], fail: [2], states: 3 },
    { name: "Educational Help", comp: [1], fail: [2], states: 3 },
    { name: "Missing Meows", comp: [2, 3, 5, 6], fail: [0], states: 7 },
    { name: "Dog Days", comp: [4, 5], fail: [], states: 6 },
    { name: "Harboring a Fugitive", comp: [7, 6], fail: [8], states: 9 },
    { name: "Ugly Duckling", comp: [3], fail: [4], states: 5 },
    { name: "Nothing Like Housework", comp: [4], fail: [], states: 5 },
    { name: "Shades of the Past", comp: [10], fail: [1, 9], states: 11 },
    { name: "Mad Cow", comp: [3, 4, 5], fail: [], states: 6 },
    { name: "Getting into the Closet", comp: [3, 5], fail: [], states: 6 },
    { name: "Farmhand's Freeholds", comp: [2], fail: [], states: 3 },
    { name: "Inheriter of the Idols", comp: [4], fail: [], states: 5 },
    { name: "Blacksmith's New Clothes", comp: [3], fail: [], states: 4 },
    { name: "Land of Milky Honey", comp: [9], fail: [], states: 10 },
    { name: "Den of Foxes", comp: [5], fail: [], states: 6 },
    { name: "Quintessentials", comp: [3], fail: [], states: 4 },
    { name: "Meet and Greet", comp: [1], fail: [], states: 2 },
    { name: "For Want of a Nail", comp: [2, 3], fail: [], states: 4 },
    { name: "The Demon of Ice", comp: [6, 7], fail: [], states: 8 },
    { name: "Ninja Stylin'", comp: [3], fail: [], states: 4 },
    { name: "Artifice Testing", comp: [3], fail: [], states: 4 },
    { name: "Winter Wolf", comp: [13], fail: [14], states: 15 },
    { name: "Sweetest Climax", comp: [3], fail: [], states: 4 },
    { name: "Father Where Art Thou?", comp: [2], fail: [], states: 3 },
    { name: "Winterstem for Aurera", comp: [1], fail: [], states: 2 },
    { name: "I Ain't Afraid of No Ghost", comp: [3], fail: [], states: 4 },
    { name: "Divine Pussy", comp: [7], fail: [], states: 8 },
    { name: "The Wyld Hunt", comp: [2], fail: [], states: 3 },
    { name: "I’ll Make a Man out of You", comp: [1], fail: [], states: 2 },
    { name: "Large is Justice", comp: [1], fail: [], states: 2 },
    { name: "The Siege of Khor'minos", comp: [15, 16], fail: [], states: 17 },
    { name: "Redemption", comp: [], fail: [], states: 3 },
    { name: "Spidernets", comp: [4], fail: [], states: 5 },
    { name: "Family Matters", comp: [3, 6, 7, 8], fail: [5], states: 9 },
    { name: "Hot Wings & Thighs", comp: [4], fail: [], states: 5 },
    { name: "Wayfort Renovations", comp: [3], fail: [], states: 4 },
    { name: "Wayfort Upgrades", comp: [3], fail: [], states: 4 },
    { name: "The Pale Flame", comp: [3], fail: [], states: 4 },
    { name: "Dye-ing to Get to Know You", comp: [5, 6], fail: [], states: 7 },
    { name: "A Dragon in the Roost", comp: [3], fail: [], states: 4 },
    { name: "Rehoming the Centaurs", comp: [2], fail: [], states: 3 },
    { name: "Work-life Balance", comp: [1], fail: [], states: 2 },
    { name: "High Ground", comp: [4], fail: [3], states: 5 },
    { name: "A Teatime For Dragons", comp: [5], fail: [], states: 6 },
    { name: "Maids of Wayfort", comp: [5], fail: [], states: 6 },
    { name: "Matiha's Revenge", comp: [2], fail: [], states: 3 },
    { name: "Attitude Adjustment", comp: [5], fail: [], states: 6 },
    { name: "Dungeoneering", comp: [3], fail: [], states: 4 },
    { name: "The Ring of Fate", comp: [4], fail: [0], states: 5 },
    { name: "Big Bad Wolf", comp: [2], fail: [0], states: 3 },
    { name: "Shadows Over the Sun", comp: [9], fail: [], states: 10 },
    { name: "Be Witched", comp: [8, 9], fail: [10, 11], states: 12 },
    { name: "Vision Quest", comp: [11], fail: [], states: 12 },
    { name: "Horn of Tides", comp: [1], fail: [], states: 2 },
    { name: "Ruins of Xadaron", comp: [4], fail: [], states: 5 },
    { name: "Monstrous Tailoring", comp: [4], fail: [], states: 5 },
    { name: "Kalysea's Offerings", comp: [5], fail: [], states: 6 },
    { name: "Golden Carrot", comp: [5], fail: [], states: 6 },
    { name: "Velun's Sword", comp: [2], fail: [], states: 3 },
    { name: "Courting The Cowgirl", comp: [9], fail: [], states: 10 },
    { name: "Courting The Bull", comp: [4], fail: [], states: 5 },
    { name: "Crystal Clear", comp: [3], fail: [], states: 4 },
    { name: "Stepping Up", comp: [2], fail: [], states: 3 },
    { name: "A Taste of Draconic Power", comp: [7], fail: [2], states: 8 },
    { name: "Saving Tarah", comp: [5, 6], fail: [], states: 7 },
    { name: "Unlikely Prospect", comp: [3], fail: [4], states: 5 },
    { name: "The Black Knight", comp: [1], fail: [], states: 2 },
    { name: "Nightmemory", comp: [5], fail: [], states: 6 },
    { name: "A Relic of Repute", comp: [6], fail: [], states: 7 },
    { name: "Howling in the Dark", comp: [9], fail: [], states: 10 },
    { name: "Strange Bedfellows", comp: [4, 10], fail: [12], states: 13 },
    {
        name: "Over Troubled Water",
        comp: [16, 17, 19],
        fail: [2, 9, 18],
        states: 20
    },
    { name: "Ill Fated Rescue", comp: [4], fail: [], states: 5 },
    { name: "Homecoming", comp: [1], fail: [], states: 2 },
    { name: "Big Bull, Tiny Closet", comp: [5], fail: [], states: 6 },
    { name: "Mystic Mischief", comp: [2], fail: [], states: 3 },
    { name: "Nash's Lost Delivery", comp: [2], fail: [], states: 3 },
    { name: "Trouble in Khor'minos", comp: [2], fail: [], states: 3 },
    { name: "Giving the Bull His Horn", comp: [1], fail: [], states: 2 },
    { name: "Alienation", comp: [3], fail: [], states: 4 },
    { name: "At the Edge of the World", comp: [], fail: [], states: 1 },
    { name: "Velun's Daughters", comp: [], fail: [], states: 1 },
    { name: "Uplifting", comp: [5], fail: [], states: 6 }
] as const;
